In [ ]:
import logging
import json
import numpy as np
from datetime import datetime, timedelta

In [2]:
import matlab.engine

# Start MATLAB
eng = matlab.engine.start_matlab()

In [3]:
# Add path if needed
eng.addpath(r'./matlab_code', nargout=0)

eng.eval("P00_Main", nargout=0)

In [11]:
ts = eng.workspace['ts']

In [ ]:
type(ts)

matlab.object

In [21]:
ts_str = eng.eval("cellstr(datestr(ts, 'yyyy-mm-ddTHH:MM:SS'))", nargout=1)
python_datetimes = [datetime.fromisoformat(s) for s in ts_str]


In [24]:
def get_matlab_ts():
    """
    Get the MATLAB timestamp as a list of strings.
    """
    ts_str = eng.eval("cellstr(datestr(ts, 'yyyy-mm-ddTHH:MM:SS'))", nargout=1)
    python_datetimes = [datetime.fromisoformat(s) for s in ts_str]
    return python_datetimes

In [25]:
get_matlab_ts()

[datetime.datetime(2025, 4, 10, 12, 0),
 datetime.datetime(2025, 4, 10, 12, 1),
 datetime.datetime(2025, 4, 10, 12, 2),
 datetime.datetime(2025, 4, 10, 12, 3),
 datetime.datetime(2025, 4, 10, 12, 4),
 datetime.datetime(2025, 4, 10, 12, 5),
 datetime.datetime(2025, 4, 10, 12, 6),
 datetime.datetime(2025, 4, 10, 12, 7),
 datetime.datetime(2025, 4, 10, 12, 8),
 datetime.datetime(2025, 4, 10, 12, 9),
 datetime.datetime(2025, 4, 10, 12, 10),
 datetime.datetime(2025, 4, 10, 12, 11),
 datetime.datetime(2025, 4, 10, 12, 12),
 datetime.datetime(2025, 4, 10, 12, 13),
 datetime.datetime(2025, 4, 10, 12, 14),
 datetime.datetime(2025, 4, 10, 12, 15),
 datetime.datetime(2025, 4, 10, 12, 16),
 datetime.datetime(2025, 4, 10, 12, 17),
 datetime.datetime(2025, 4, 10, 12, 18),
 datetime.datetime(2025, 4, 10, 12, 19),
 datetime.datetime(2025, 4, 10, 12, 20),
 datetime.datetime(2025, 4, 10, 12, 21),
 datetime.datetime(2025, 4, 10, 12, 22),
 datetime.datetime(2025, 4, 10, 12, 23),
 datetime.datetime(2025, 4

In [19]:
from datetime import datetime

# Convert MATLAB string array to Python list of datetime objects
python_datetimes = [datetime.fromisoformat(s) for s in ts_str]


In [22]:
python_datetimes

[datetime.datetime(2025, 4, 10, 12, 0),
 datetime.datetime(2025, 4, 10, 12, 1),
 datetime.datetime(2025, 4, 10, 12, 2),
 datetime.datetime(2025, 4, 10, 12, 3),
 datetime.datetime(2025, 4, 10, 12, 4),
 datetime.datetime(2025, 4, 10, 12, 5),
 datetime.datetime(2025, 4, 10, 12, 6),
 datetime.datetime(2025, 4, 10, 12, 7),
 datetime.datetime(2025, 4, 10, 12, 8),
 datetime.datetime(2025, 4, 10, 12, 9),
 datetime.datetime(2025, 4, 10, 12, 10),
 datetime.datetime(2025, 4, 10, 12, 11),
 datetime.datetime(2025, 4, 10, 12, 12),
 datetime.datetime(2025, 4, 10, 12, 13),
 datetime.datetime(2025, 4, 10, 12, 14),
 datetime.datetime(2025, 4, 10, 12, 15),
 datetime.datetime(2025, 4, 10, 12, 16),
 datetime.datetime(2025, 4, 10, 12, 17),
 datetime.datetime(2025, 4, 10, 12, 18),
 datetime.datetime(2025, 4, 10, 12, 19),
 datetime.datetime(2025, 4, 10, 12, 20),
 datetime.datetime(2025, 4, 10, 12, 21),
 datetime.datetime(2025, 4, 10, 12, 22),
 datetime.datetime(2025, 4, 10, 12, 23),
 datetime.datetime(2025, 4

In [ ]:
time_np = np.array(ts)

In [14]:
from datetime import datetime, timedelta
# Convert to Python list of datetime.datetime
python_datetimes = [
    datetime(d.year, d.month, d.day, d.hour, d.minute, int(d.second))
    for d in ts
]

# Now `python_datetimes` is a standard Python list of datetime objects
print(python_datetimes[:5])  # show first 5 as a preview

AttributeError: 'matlab.object' object has no attribute 'year'

In [8]:
eng.eval("stepScenario", nargout=0)

In [10]:
type(eng.workspace['ChannelListLeo'])

matlab.double

In [11]:
# Access the variable from MATLAB workspace
channel_list_leo = eng.workspace['ChannelListLeo']

import numpy as np

# Convert MATLAB array to NumPy array
channel_list_leo_np = np.array(channel_list_leo)


In [13]:
channel_list_leo_np.shape

(20, 588, 61)

In [ ]:
channel_list_leo_np[0, 0, :]

array([16.,  5., 13., 12.,  3., 24.,  6., 22., 23.,  2.,  6.,  9., 19.,
       12., 20.,  7., 10., 16., 21., 24.,  4., 15., 13., 13., 14.,  6.,
       23.,  6., 18., 18.,  1., 23.,  8., 19., 21.,  9.,  6., 22., 14.,
        8., 25., 21., 21., 23., 11.,  6., 14.,  8.,  4., 15.,  9.,  4.,
       23.,  1.,  4.,  2.,  4., 16., 25., 23., 13.])

In [18]:
channel_list_leo_np[0, 0, 0] = 0 

In [25]:
channel_list_leo_np[0, 0, :]

array([ 0.,  5., 13., 12.,  3., 24.,  6., 22., 23.,  2.,  6.,  9., 19.,
       12., 20.,  7., 10., 16., 21., 24.,  4., 15., 13., 13., 14.,  6.,
       23.,  6., 18., 18.,  1., 23.,  8., 19., 21.,  9.,  6., 22., 14.,
        8., 25., 21., 21., 23., 11.,  6., 14.,  8.,  4., 15.,  9.,  4.,
       23.,  1.,  4.,  2.,  4., 16., 25., 23., 13.])

In [26]:
channel_list_leo_np[0, 0, :]

array([ 0.,  5., 13., 12.,  3., 24.,  6., 22., 23.,  2.,  6.,  9., 19.,
       12., 20.,  7., 10., 16., 21., 24.,  4., 15., 13., 13., 14.,  6.,
       23.,  6., 18., 18.,  1., 23.,  8., 19., 21.,  9.,  6., 22., 14.,
        8., 25., 21., 21., 23., 11.,  6., 14.,  8.,  4., 15.,  9.,  4.,
       23.,  1.,  4.,  2.,  4., 16., 25., 23., 13.])

In [27]:
np.array(eng.workspace['SINR'])

array([[18.6321532 , 18.1738114 , 17.39065735, ..., 17.20543613,
        17.44561847, 18.58896993],
       [18.16319211, 17.30538242, 18.08549828, ..., 17.37947523,
        18.26986927, 18.56015032],
       [17.42374332, 18.62265417, 17.35184075, ..., 17.21182997,
        17.76578274, 18.81068168],
       ...,
       [20.64317084, 19.30829737, 19.6917181 , ..., 21.06221538,
        22.61125077, 19.29726157],
       [19.24414496, 19.86530261, 20.27652475, ..., 19.55346561,
        21.53226105, 20.82383074],
       [19.47818656, 21.3687709 , 20.31451662, ..., 20.42383194,
        21.88752985, 19.05797169]])

In [28]:
np.array(eng.workspace['SINR']).shape

(20, 61)

In [21]:
eng.workspace['ChannelListLeo'] = matlab.double(channel_list_leo_np)

In [22]:
# Access the variable from MATLAB workspace
channel_list_leo = eng.workspace['ChannelListLeo']

import numpy as np

# Convert MATLAB array to NumPy array
channel_list_leo_np = np.array(channel_list_leo)


In [23]:
channel_list_leo_np

array([[[ 0.,  5., 13., ..., 25., 23., 13.],
        [ 6.,  3., 10., ...,  8.,  4., 15.],
        [21.,  6., 20., ..., 13., 12.,  5.],
        ...,
        [ 7., 15., 15., ..., 12., 20., 24.],
        [15.,  9.,  2., ...,  7.,  3.,  3.],
        [23., 15.,  7., ..., 15.,  9., 13.]],

       [[14.,  4., 19., ..., 12.,  4., 15.],
        [10.,  4.,  2., ..., 17.,  9., 10.],
        [ 3.,  8., 10., ..., 19., 14., 21.],
        ...,
        [ 6., 22.,  2., ..., 24., 17., 17.],
        [24., 22., 22., ..., 24., 12., 20.],
        [ 7.,  2.,  1., ...,  8., 14., 12.]],

       [[ 8., 12., 22., ..., 19.,  8., 14.],
        [18., 15., 24., ..., 22., 16.,  5.],
        [17., 11.,  9., ..., 25.,  2., 12.],
        ...,
        [12., 17., 23., ...,  1.,  7., 16.],
        [19., 24., 19., ..., 23., 25., 21.],
        [14.,  7.,  4., ...,  2.,  8., 11.]],

       ...,

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan

In [3]:
eng.eval("resetScenario", nargout=0)

In [4]:
leoNum = int(eng.workspace['leoNum'])
geoNum = int(eng.workspace['geoNum'])
cities = eng.workspace['cities_py']

nuser = len(cities)

In [5]:
nuser

2

In [6]:
channelFreqs = eng.workspace['channelFreqs']

In [7]:
currentLEOFreqs = eng.workspace['currentLEOFreqs']

In [8]:
currentLEOFreqs[0][0]

1502125000.0

In [9]:
eng.workspace['currentLEOFreqs'][0][0] = 0.0

In [10]:
eng.workspace['currentLEOFreqs']

matlab.double([[1502125000.0,1501375000.0,1498875000.0]])

In [11]:
#Retrieve the current value
currentLEOFreqs = eng.workspace['currentLEOFreqs']

In [12]:
np.array(currentLEOFreqs).flatten().tolist()

[1502125000.0, 1501375000.0, 1498875000.0]

In [13]:
currentLEOFreqs = np.array(currentLEOFreqs).flatten()

In [14]:
currentLEOFreqs.tolist()

[1502125000.0, 1501375000.0, 1498875000.0]

In [15]:


# #Modify the values (example change)
# new_values = [1502126000.0, 1501376000.0, 1498876000.0]

# new_values = np.array(currentLEOFreqs).flatten().tolist()

# #Update the workspace variable
# eng.workspace['currentLEOFreqs'] = matlab.double(new_values)

In [16]:
eng.workspace['currentLEOFreqs']

matlab.double([[1502125000.0,1501375000.0,1498875000.0]])

In [17]:
channelFreqs[0][0]

1498875000.0

In [18]:
type(currentLEOFreqs) == type(float(0))

False

In [19]:
len(list(channelFreqs[0]))

10

In [20]:
channelFreqs

matlab.double([[1498875000.0,1500125000.0,1500375000.0,1500625000.0,1500875000.0,1501125000.0,1501375000.0,1501625000.0,1501875000.0,1502125000.0]])

In [21]:
channelFreqs[0]

matlab.double([1498875000.0,1500125000.0,1500375000.0,1500625000.0,1500875000.0,1501125000.0,1501375000.0,1501625000.0,1501875000.0,1502125000.0])

In [22]:
print("Leo Satelitte ID",eng.workspace['leoIndex'])
print("Time Index",eng.workspace['tIdx'])

Leo Satelitte ID 0.0
Time Index 1.0


In [23]:
eng.eval("stepScenario", nargout=0)
done = eng.workspace['done']
state = eng.workspace['snd_state']
reward = eng.workspace['reward']
print(state)
print(reward)
print(f"Step, done: {done}")
print("Leo Satelitte ID",eng.workspace['leoIndex'])
print("Time Index",eng.workspace['tIdx'])

{'GeobaseFreq': 1500000000.0, 'time': '10-Apr-2025 12:00:00', 'LEO_1': {'LEO_Num': 1.0, 'Latitude': -65.25349692661547, 'Longitude': 131.1964150359908, 'AccessStatus': {'Melbourne': False, 'Sydney': False}}, 'LEO_2': {'LEO_Num': 2.0, 'Latitude': -65.26423381451286, 'Longitude': 141.24393291499436, 'AccessStatus': {'Melbourne': False, 'Sydney': False}}, 'LEO_3': {'LEO_Num': 3.0, 'Latitude': -65.2709744633676, 'Longitude': 151.294798696656, 'AccessStatus': {'Melbourne': False, 'Sydney': False}}}
{'LEO_1': {'LEO_Num': 1.0, 'reward': {}}, 'LEO_2': {'LEO_Num': 2.0, 'reward': {}}, 'LEO_3': {'LEO_Num': 3.0, 'reward': {}}, 'GEO_1': {'GEO_Num': 1.0, 'reward': {'Melbourne': {'rssi': -103.85697683401858, 'snr': 47.06321417901818}, 'Sydney': {'rssi': -104.54193280099128, 'snr': 46.37825821204548}}}}
Step, done: False
Leo Satelitte ID 1.0
Time Index 1.0


In [24]:
print("Leo Satelitte ID",eng.workspace['leoIndex'])
print("Time Index",eng.workspace['tIdx'])

Leo Satelitte ID 1.0
Time Index 1.0


In [25]:
for i in range(20):
    eng.eval("stepScenario", nargout=0)
    done = eng.workspace['done']
    state = eng.workspace['snd_state']
    reward = eng.workspace['reward']
    print(state)
    print(reward)
    print(f"Step {i+1}, done: {done}")
    print("Leo Satelitte ID",eng.workspace['leoIndex'])
    print("Time Index",eng.workspace['tIdx'])
    if done:
        break

# eng.eval("SaveData", nargout=0)


print(reward)

{'GeobaseFreq': 1500000000.0, 'time': '10-Apr-2025 12:00:00', 'LEO_1': {'LEO_Num': 1.0, 'Latitude': -65.25349692661547, 'Longitude': 131.1964150359908, 'AccessStatus': {'Melbourne': False, 'Sydney': False}}, 'LEO_2': {'LEO_Num': 2.0, 'Latitude': -65.26423381451286, 'Longitude': 141.24393291499436, 'AccessStatus': {'Melbourne': False, 'Sydney': False}}, 'LEO_3': {'LEO_Num': 3.0, 'Latitude': -65.2709744633676, 'Longitude': 151.294798696656, 'AccessStatus': {'Melbourne': False, 'Sydney': False}}}
{'LEO_1': {'LEO_Num': 1.0, 'reward': {}}, 'LEO_2': {'LEO_Num': 2.0, 'reward': {}}, 'LEO_3': {'LEO_Num': 3.0, 'reward': {}}, 'GEO_1': {'GEO_Num': 1.0, 'reward': {'Melbourne': {'rssi': -103.85697683401858, 'snr': 47.06321417901818}, 'Sydney': {'rssi': -104.54193280099128, 'snr': 46.37825821204548}}}}
Step 1, done: False
Leo Satelitte ID 2.0
Time Index 1.0
{'GeobaseFreq': 1500000000.0, 'time': '10-Apr-2025 12:00:00', 'LEO_1': {'LEO_Num': 1.0, 'Latitude': -65.25349692661547, 'Longitude': 131.19641503

In [ ]:
print("Saving MATLAB Data.")
eng.eval("SaveData", nargout=0)

Saving MATLAB Data.


: 

In [ ]:
eng.workspace['logData']

ValueError: only a scalar struct can be returned from MATLAB

In [ ]:
eng.workspace['reward_data_geo_gs']

{'Melbourne': {'rssi': -103.85695654133828, 'snr': 47.06323447169848},
 'Sydney': {'rssi': -104.5419147377656, 'snr': 46.37827627527117}}

In [ ]:
eng.workspace['reward_data_leo_gs']

{'Melbourne': {'rssi': -176.09455199342835, 'snr': -25.17436098039161},
 'Sydney': {'rssi': -183.33174225993244, 'snr': -32.4115512468957}}

In [ ]:
eng.workspace['reward_data_leo']

{'LEO_Num': 1.0,
 'reward': {'Melbourne': {'rssi': -176.09455199342835,
   'snr': -25.17436098039161},
  'Sydney': {'rssi': -183.33174225993244, 'snr': -32.4115512468957}}}

In [ ]:
print(state)

{'GeobaseFreq': 1500000000.0, 'time': '10-Apr-2025 12:03:20', 'LEO_1': {'LEO_Num': 1.0, 'Latitude': -52.99087266793843, 'Longitude': 130.42141382607795, 'AccessStatus': {'Melbourne': True, 'Sydney': True}}}


In [ ]:
state['LEO_1']['AccessStatus']['Melbourne']

True

In [ ]:
reward = eng.workspace['reward']

In [ ]:
reward

{'LEO_1': {'LEO_Num': 1.0,
  'reward': {'Melbourne': {'rssi': -176.09455199342835,
    'snr': -25.17436098039161},
   'Sydney': {'rssi': -183.33174225993244, 'snr': -32.4115512468957}}},
 'GEO_1': {'GEO_Num': 1.0,
  'reward': {'Melbourne': {'rssi': -103.85695654133828,
    'snr': 47.06323447169848},
   'Sydney': {'rssi': -104.5419147377656, 'snr': 46.37827627527117}}}}

In [ ]:
reward["LEO_1"]['reward']['Melbourne']['snr']

-25.17436098039161

In [ ]:
reward["LEO_1"]['reward']

{'Melbourne': {'rssi': -176.09455199342835, 'snr': -25.17436098039161},
 'Sydney': {'rssi': -183.33174225993244, 'snr': -32.4115512468957}}

In [ ]:
np.array(reward["LEO_1"]['reward']['Melbourne']['snr'])

array(-25.17436098)

In [ ]:
eng.eval("reward.('LEO_1').('reward').('Melbourne').('snr')")

-25.17436098039161

In [ ]:
snr_value = eng.eval("reward.('LEO_1').('reward').('Melbourne').('snr')")


In [ ]:
print(type(snr_value))  # Should be something like <class 'matlab.double'>
print(snr_value)


<class 'float'>
-25.17436098039161


In [ ]:
print(state)
print(reward)

{'GeobaseFreq': 1500000000.0, 'time': '10-Apr-2025 12:03:20', 'LEO_1': {'LEO_Num': 1.0, 'Latitude': -52.99087266793843, 'Longitude': 130.42141382607795, 'AccessStatus': {'Melbourne': True, 'Sydney': True}}}
{'LEO_1': {'LEO_Num': 1.0, 'reward': {'Melbourne': {'rssi': -176.09455199342835, 'snr': -25.17436098039161}, 'Sydney': {'rssi': -183.33174225993244, 'snr': -32.4115512468957}}}, 'GEO_1': {'GEO_Num': 1.0, 'reward': {'Melbourne': {'rssi': -103.85695654133828, 'snr': 47.06323447169848}, 'Sydney': {'rssi': -104.5419147377656, 'snr': 46.37827627527117}}}}


In [ ]:
import numpy as np

if isinstance(snr_value, list):  # likely [[value]]
    snr_array = np.array(snr_value)
    snr_scalar = snr_array.item()
else:
    snr_scalar = float(snr_value)

print("Correct SNR:", snr_scalar)


Correct SNR: -25.17436098039161


In [ ]:
# In MATLAB via Python, convert SNR to string
eng.eval("temp_snr_str = num2str(reward.('LEO_1').('reward').('Melbourne').('snr'));", nargout=0)

# Pull the string into Python
snr_str = eng.workspace["temp_snr_str"]
snr_value = float(snr_str)

print("SNR (via string conversion):", snr_value)


SNR (via string conversion): -25.1744


In [ ]:
eng.eval("temp_snr = reward.('LEO_1').('reward').('Melbourne').('snr');", nargout=0)
raw_value = eng.workspace["temp_snr"]

print("Type:", type(raw_value))
print("Raw value:", raw_value)


Type: <class 'float'>
Raw value: -25.17436098039161


In [ ]:
import gymnasium as gym

In [ ]:
state

{'GeobaseFreq': 1500000000.0,
 'time': '10-Apr-2025 12:03:20',
 'LEO_1': {'LEO_Num': 1.0,
  'Latitude': -52.99087266793843,
  'Longitude': 130.42141382607795,
  'AccessStatus': {'Melbourne': True, 'Sydney': True}}}

In [ ]:
from gymnasium.spaces import MultiDiscrete, Dict, Box

In [ ]:
observation_space = Dict({
            "utc_time": Box(low=-np.inf, high=np.inf, shape=(1,), dtype=np.int64),
            "leo_pos": Box(low=-np.inf, high=np.inf, shape=(leoNum *2,), dtype=np.float64),
            "geo_freq": Box(low=-np.inf, high=np.inf, shape=(geoNum,), dtype=np.float64),
            "leo_freq": Box(low=-np.inf, high=np.inf, shape=(leoNum,), dtype=np.float64),
            "leo_access": Box(low=0, high=1, shape=(leoNum* nuser,), dtype=np.float64),
        })

In [ ]:
def convert_matlab_state_to_py_state(cur_state_from_matlab=None):
    # Log cur_state_from_matlab
    logging.info("=== Current State ===")
    logging.info(json.dumps(cur_state_from_matlab, indent=2))
    """Reset the environment and initialize the buffer."""
    global cur_obs
    global step_count
    step_count = 0
    from datetime import datetime, timezone

    # 1. utc_time (convert string to UNIX timestamp in seconds)
    dt = datetime.strptime(cur_state_from_matlab["time"], "%d-%b-%Y %H:%M:%S")
    utc_timestamp = int(dt.timestamp())
    cur_obs["utc_time"] = np.array([utc_timestamp], dtype=np.int64)

    # 2. leo_pos (interleaved lat/lon)
    leo_pos = []
    for i in range(1, leoNum + 1):
        leo = cur_state_from_matlab[f"LEO_{i}"]
        leo_pos.extend([leo["Latitude"], leo["Longitude"]])
    cur_obs["leo_pos"] = np.array(leo_pos, dtype=np.float64)

    # 3. geo_freq
    cur_obs["geo_freq"] = np.array([cur_state_from_matlab["GeobaseFreq"]], dtype=np.float64)

    # 4. leo_freq (not in cur_state_from_matlab — fill with zeros or placeholder)
    cur_obs["leo_freq"] = np.zeros(leoNum, dtype=np.float64)

    # 5. leo_access (flattened [LEO1_Melb, LEO1_Syd, LEO2_Melb, ..., LEO3_Syd])
    leo_access = []
    for i in range(1, leoNum + 1):
        access = cur_state_from_matlab[f"LEO_{i}"]["AccessStatus"]
        leo_access.extend([
            float(access["Melbourne"]),
            float(access["Sydney"])
        ])
    cur_obs["leo_access"] = np.array(leo_access, dtype=np.float64)

    # (Optional) Validate against observation_space
    assert observation_space.contains(cur_obs), "cur_obs doesn't match the observation space!"

    return cur_obs

In [ ]:
cur_obs = None

In [ ]:
intial_obs = {
    "utc_time": np.array([0], dtype=np.int64),
    "leo_pos": np.random.randn(leoNum * 2).astype(np.float64),  # e.g., [x1, y1, x2, y2, x3, y3]
    "geo_freq": np.random.uniform(10.5, 12.0, size=(geoNum,)).astype(np.float64),
    "leo_freq": np.random.uniform(20.0, 22.0, size=(leoNum,)).astype(np.float64),
    "leo_access": np.random.randint(0, 2, size=(leoNum * nuser,)).astype(np.float64),
} 

In [ ]:
cur_obs = intial_obs.copy() if cur_obs is None else intial_obs.copy()

In [ ]:
convert_matlab_state_to_py_state(state)

{'utc_time': array([1744250600], dtype=int64),
 'leo_pos': array([-52.99087267, 130.42141383]),
 'geo_freq': array([1.5e+09]),
 'leo_freq': array([0.]),
 'leo_access': array([1., 1.])}

In [ ]:
eng.workspace['done']

False

In [ ]:
eng.workspace['reward']

{'LEO_1': {'LEO_Num': 1.0,
  'reward': {'Melbourne': {'rssi': -176.09455199342835,
    'snr': -25.17436098039161},
   'Sydney': {'rssi': -183.33174225993244, 'snr': -32.4115512468957}}},
 'GEO_1': {'GEO_Num': 1.0,
  'reward': {'Melbourne': {'rssi': -103.85695654133828,
    'snr': 47.06323447169848},
   'Sydney': {'rssi': -104.5419147377656, 'snr': 46.37827627527117}}}}

In [ ]:
channelFreqs = eng.workspace['channelFreqs']

In [ ]:
channelFreqs[0]

matlab.double([1498875000.0,1500125000.0,1500375000.0,1500625000.0,1500875000.0,1501125000.0,1501375000.0,1501625000.0,1501875000.0,1502125000.0])